[package]
name = "rigid_pixels"
version = "0.1.0"
edition = "2024"

[profile.dev]
overflow-checks=false

[profile.release]
overflow-checks=false
panic="abort"

[dependencies]
bitflags = { version = "2.9.2", default-features = false }
bitvec = { version = "1.0.1", default-features = false, features = [ "std" ] }
egui-macroquad = { version = "0.17.3", default-features = false }
macroquad = { version = "0.4.14", default-features = false }
slotmap = { version = "1.0.7", default-features = false }